### ISSUE TITLE
Report disabled form elements as not interactive

### ISSUE THREAD

**Issue by hidde** [matijs/is-interactive-element#8]
I think we should consider returning `false` for disabled form elements, though not explictly an exception in the [definition for interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content).

**Comment by matijs** [comment]
Did you always want to return false or could it be an idea to add a second parameter that only returns false for disabled elements when it's true?

`isInteractiveElement(element: HTMLElement, strict?: boolean)`

**Comment by hidde** [comment]
I'm going to close this as it seems irrelevant
